"""add created_at for category

Revision ID: 300fa6999c6c
Revises: f5cb2b1482b9
Create Date: 2025-11-27 15:32:44.795774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300fa6999c6c'
down_revision: Union[str, Sequence[str], None] = 'f5cb2b1482b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('create_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'create_at')
    # ### end Alembic commands ###
