"""renamed create_at to created_at for athlete

Revision ID: 34174cbab40d
Revises: e76612201ec4
Create Date: 2025-11-27 18:35:45.630743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34174cbab40d'
down_revision: Union[str, Sequence[str], None] = 'e76612201ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('athletes', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('athletes', 'created_at')
    # ### end Alembic commands ###
