"""renamed training_center_id for athlete

Revision ID: c042f392a6fb
Revises: 34174cbab40d
Create Date: 2025-11-27 18:39:47.594879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c042f392a6fb'
down_revision: Union[str, Sequence[str], None] = '34174cbab40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('training_center_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('athletes_training_cente_id_fkey'), 'athletes', type_='foreignkey')
    op.create_foreign_key(None, 'athletes', 'training_centers', ['training_center_id'], ['pk_id'])
    op.drop_column('athletes', 'training_cente_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('training_cente_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    op.create_foreign_key(op.f('athletes_training_cente_id_fkey'), 'athletes', 'training_centers', ['training_cente_id'], ['pk_id'])
    op.drop_column('athletes', 'training_center_id')
    # ### end Alembic commands ###
