"""add created_at for training center

Revision ID: d1bd6aa6eb4b
Revises: d4f807acd036
Create Date: 2025-11-27 17:56:28.173045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bd6aa6eb4b'
down_revision: Union[str, Sequence[str], None] = 'd4f807acd036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_centers', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_centers', 'created_at')
    # ### end Alembic commands ###
