"""renamed create_at to created_at for category

Revision ID: d4f807acd036
Revises: 300fa6999c6c
Create Date: 2025-11-27 15:35:48.212411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4f807acd036'
down_revision: Union[str, Sequence[str], None] = '300fa6999c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('categories', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
