"""modified athlete table adding category and training center

Revision ID: e76612201ec4
Revises: d1bd6aa6eb4b
Create Date: 2025-11-27 18:15:44.654522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76612201ec4'
down_revision: Union[str, Sequence[str], None] = 'd1bd6aa6eb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
